### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by Hiramdu** [WhatAShot/DANet#3]
Hi I have a error when inference. May you help check how to solve it? Thank you

I use the best model
Traceback (most recent call last):
  File "predict.py", line 58, in <module>
    clf.load_model(filepath, input_dim=X_test.shape[1], output_dim=output_dim, n_gpu=n_gpu)
  File "/home/DANet/abstract_model.py", line 223, in load_model
    self.layer, self.virtual_batch_size = load_model['layer_num'], load_model['virtual_batch_size']
TypeError: 'DANet' object is not subscriptable

I use the checkpoint model:
Traceback (most recent call last):
  File "predict.py", line 58, in <module>
    clf.load_model(filepath, input_dim=X_test.shape[1], output_dim=output_dim, n_gpu=n_gpu)
  File "/home/gdu/DANet/abstract_model.py", line 223, in load_model
    self.layer, self.virtual_batch_size = load_model['layer_num'], load_model['virtual_batch_size']
KeyError: 'layer_num'

**Comment by kkk55596** [comment]
It seems you didn't download the model weights.
You can find a DANet-32 weights for forest_cover_type here: https://github.com/WhatAShot/DANet/tree/main/weights
Ex: python predict.py -d forest -m [weight_path]

**Comment by Hiramdu** [comment]
Hi I trained cardio model, and I download the model weights here: checkpoint.pth. Is it right?

<img width="653" alt="Screen Shot 2021-12-23 at 10 30 34 AM" src="https://user-images.githubusercontent.com/19141771/147261327-6c7f2883-18f8-4923-a710-3284ecb56633.png">

**Comment by kkk55596** [comment]
Use best.pth for inferencing not checkpoint.pth
"checkpoint.pth" is only for resuming the training state.

**Comment by Hiramdu** [comment]
Hi I use the best.pth, it has an error, may you help?

Traceback (most recent call last):
  File "predict.py", line 58, in <module>
    clf.load_model(filepath, input_dim=X_test.shape[1], output_dim=output_dim, n_gpu=n_gpu)
  File "/home/DANet/abstract_model.py", line 223, in load_model
    print(load_model.keys)
  File "/home/DANet/env37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'DANet' object has no attribute 'keys'

**Comment by Hiramdu** [comment]
> Use best.pth for inferencing not checkpoint.pth "checkpoint.pth" is only for resuming the training state.

Hi I use best.pth, the same error as the beginning
Traceback (most recent call last):
  File "predict.py", line 58, in <module>
    clf.load_model(filepath, input_dim=X_test.shape[1], output_dim=output_dim, n_gpu=n_gpu)
  File "/home/DANet/abstract_model.py", line 223, in load_model
    self.layer, self.virtual_batch_size = load_model['layer_num'], load_model['virtual_batch_size']
TypeError: 'DANet' object is not subscriptable

**Comment by Hiramdu** [comment]
It seems abstract_model.py had some error when read the layer_num and virtual_batch_size?

**Comment by kkk55596** [comment]
We have fixed this bug. You can download the newest callback.py in "lib" for solving this problem.
Thank you for the report.

**Comment by Hiramdu** [comment]
Thank you! That works now!
